=== lgorich/WebServices/example.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="sandwiches" type="sandwichesType"/>

  <xs:complexType name="topType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="sort" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="midlleType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="sort" use="optional"/>
        <xs:attribute type="xs:string" name="fresh" use="optional"/>
        <xs:attribute type="xs:integer" name="quantity" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="ingridientsType">
    <xs:sequence>
      <xs:element type="topType" name="top" minOccurs="0"/>
      <xs:element type="midlleType" name="midlle" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element name="bottom">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute type="xs:string" name="sort" use="optional"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>

  <xs:complexType name="bottomType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="sort" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="sandwichesType">
    <xs:sequence>
      <xs:element type="ingridientsType" name="ingridients" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== lgorich/WebServices/example.xml
<?xml version="1.0" encoding="UTF-8" ?>

<sandwiches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="example.xsd">

    <ingridients name="taste_and_pretty">
        <top sort="white-normal">bread</top>
        <midlle sort="big-holes">cheese</midlle>
        <midlle sort="salami">sausage</midlle>
        <midlle>salad</midlle>
        <bottom>pita</bottom>
    </ingridients>

    <ingridients name="tasteless_and_ugly">
        <midlle fresh="look_like">fish</midlle>
        <midlle>cheese</midlle>
        <midlle>cucumber</midlle>
        <midlle sort="pepper_and_strawberry">mayonnaise</midlle>
        <bottom sort="black_and_blue">bread</bottom>
    </ingridients>

    <ingridients name="uncertain3000">
        <top>pita</top>
        <midlle fresh="100% new, was three days ago..." sort="look_like_salmon">fish</midlle>
        <bottom>bread</bottom>
    </ingridients>

    <ingridients name="BLT">
        <top sort="white-normal">bread</top>
        <midlle fresh="fresh">lettuce</midlle>
        <midlle quantity="3" sort="streaky">bacon</midlle>
        <midlle fresh="fresh">tomato</midlle>
        <bottom sort="white-normal">bread</bottom>
    </ingridients>

</sandwiches>
